### ISSUE TITLE
cachetools conflict with firebase-admin

### ISSUE THREAD

**Issue by dgaedcke** [cloudendpoints/endpoints-python#191]
You require:
google-endpoints-api-management
which is also requiring:
google-auth

but firebase-admin depends upon:
google-api-core which requires :
google-auth<2.0dev,>=0.4.0

so I'm getting this error:
google-auth 1.6.3 has requirement cachetools>=2.0.0, but you'll have cachetools 1.1.6 which is incompatible.

Also can you please make a note on the README.MD that using endpoints FORCES you to ignore advice elsewhere on the net to use virtualenv (instead of vendoring) with GAE-standard

**Comment by dgaedcke** [comment]
author of firebase-admin has kicked this over to you
https://github.com/firebase/firebase-admin-python/issues/269#issuecomment-472594642

**Comment by inklesspen** [comment]
google-endpoints-api-management does not require google-auth. It does require `cachetools < 2`. The most common reason for an upward bound on versions is that the new version does not function on App Engine. The second most common reason is that we have a dependency which requires an older version. I don't know the exact reason for this upward bound.

This issue is properly tracked in https://github.com/cloudendpoints/endpoints-management-python/issues/72, so I'm closing it here.

**Comment by ubragg** [comment]
> This issue is properly tracked in [cloudendpoints/endpoints-management-python#72](https://github.com/cloudendpoints/endpoints-management-python/issues/72), so I'm closing it here.

There has been no movement on this bug over there since it was filed, despite a trivial PR that was submitted to no response for over 4 months.

Given that this library is the one I actually use, and it currently isn't compatible with the google-cloud (or firebase-admin) library, is there any overlap in the teams that might help shake the tree a bit?  Or have the cloudendpoints libraries been completely abandoned?
